### ISSUE TITLE
Randomly restarting/ crashing

### ISSUE THREAD

**Issue by DJCoolDev** [Gelbpunkt/gateway-proxy#15]
Once I start the proxy with my production bot token and 75 shards (~100k guilds) it randomly restarts/ crashes after some time while it's still starting and spawning shards. Screenshot below. I would appreciate any help.
![image](https://user-images.githubusercontent.com/66355549/229214793-d00319de-9807-4565-8374-e99070c44ae7.png)

**Comment by Gelbpunkt** [comment]
Hi there, I cannot reproduce this. Running my 250 shards works completely fine on the latest build. Can you send me your configuration file (please omit the token) and tell me how exactly you're running it (inside docker/podman/whatever your setup is) so I can reproduce it?

**Comment by DJCoolDev** [comment]
Hey, I'm running it over docker and my config file is the following, providing the token as a ENV variable:
`{
  "log_level": "debug",
  "intents": 38401,
  "shards": 75,
  "port": 7878,
  "activity": {
    "type": 2,
    "name": "/help"
  },
  "status": "online",
  "externally_accessible_url": "ws://<IP REMOVED>:7878",
  "cache": {
    "channels": true,
    "presences": false,
    "emojis": false,
    "current_member": true,
    "members": true,
    "roles": true,
    "stage_instances": false,
    "stickers": false,
    "users": false,
    "voice_states": false
  }
}`. 

It could be that I'm a bit stupid and tried to deploy the proxy on some nodes that had too high memory usage. I'll move it to another node with like 32GB RAM left and let you know if this solved the issue.

**Comment by DJCoolDev** [comment]
Random restarts seem to be fixed on the new node. However, the bot now gives me a lot of warnings saying `Shard ID x heartbeat blocked for more than 10 seconds.`.

**Comment by Gelbpunkt** [comment]
> Random restarts seem to be fixed on the new node. However, the bot now gives me a lot of warnings saying `Shard ID x heartbeat blocked for more than 10 seconds.`.

Are you using discord.py? This happened to me too because the latency to the proxy is so low, it receives the heartbeat instantly and believes it didn't get one. I completely removed heartbeating in my fork because of this.

**Comment by DJCoolDev** [comment]
Yeah I‘m using discord.py

**Comment by DJCoolDev** [comment]
I've removed heartbeating and that solved the problem! Thanks for your help, it was very very helpful and useful!
