### ISSUE TITLE
Graceful shutdown support

### ISSUE THREAD

**Issue by laggron42** [Gelbpunkt/gateway-proxy#18]
Hi,

I have been using this proxy to run my bot with 240 shards and it works great, thank you for your work!

I was wondering if it's possible to add support for a proper disconnection (as described [here](https://discord.com/developers/docs/topics/gateway#initiating-a-disconnect)) from the gateway in certain conditions (for instance receiving a SIGTERM signal).

This would allow the bot to actually show up as disconnected instead of staying connected for 5 minutes and confusing users when the intent is to actually shut down everything.

**Comment by Gelbpunkt** [comment]
That should be implemented as of 1bf68e2418ab3b80b9cee24ad6f13210fc325535.
