### ISSUE TITLE
Requesting guild chunks takes a lot of time since the switch to tokio-websockets library

### ISSUE THREAD

**Issue by PredaaA** [Gelbpunkt/gateway-proxy#19]
Since this commit https://github.com/Gelbpunkt/gateway-proxy/commit/e41d6a48054e824493f3893ba38b10a668afe432 I'm mostly unable to chunk guilds, using discord.py, I'm seeing "Shard ID %s timed out waiting for chunks for guild_id %s."
For reference https://github.com/Rapptz/discord.py/blob/a5d03d4a1e6f4314518f6f55d8b7130ab3f4336e/discord/state.py#L577. I have tried to increase this manually to 1 minute but it still couldn't get chunks.

I have switched back to tokio_tungstenite on a fork and it's all working correctly.

**Comment by Gelbpunkt** [comment]
Can you provide logs please? I doubt that this is a websocket library issue.

**Comment by Gelbpunkt** [comment]
I believe this is a discord.py issue that was fixed in dpy 2.4.
