### ISSUE TITLE
Caching error

### ISSUE THREAD

**Issue by cheesycod** [Gelbpunkt/gateway-proxy#20]
Seems to have an issue with caching

Dec 06 03:33:01 hepatitis splashtail[609387]: Flare (0) [ERROR] [Discord] => Uncaught Exception TypeError: Cannot read properties of undefined (reading 'length')
Dec 06 03:33:01 hepatitis splashtail[609387]:     at GuildEmoji.equals (/home/antiraid/splashtail/staging/bot/node_modules/discord.js/src/structures/GuildEmoji.js:141:21)
Dec 06 03:33:01 hepatitis splashtail[609387]:     at GuildEmojisUpdateAction.handle (/home/antiraid/splashtail/staging/bot/node_modules/discord.js/src/client/actions/GuildEmojisUpdate.js:17:26)
Dec 06 03:33:01 hepatitis splashtail[609387]:     at Guild._patch (/home/antiraid/splashtail/staging/bot/node_modules/discord.js/src/structures/Guild.js:451:45)
Dec 06 03:33:01 hepatitis splashtail[609387]:     at module.exports [as GUILD_CREATE] (/home/antiraid/splashtail/staging/bot/node_modules/discord.js/src/client/websocket/handlers/GUILD_CREATE.js:11:13)
Dec 06 03:33:01 hepatitis splashtail[609387]:     at WebSocketManager.handlePacket (/home/antiraid/splashtail/staging/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:355:31)
Dec 06 03:33:01 hepatitis splashtail[609387]:     at WebSocketManager.<anonymous> (/home/antiraid/splashtail/staging/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:239:12)
Dec 06 03:33:01 hepatitis splashtail[609387]:     at WebSocketManager.emit (/home/antiraid/splashtail/staging/bot/node_modules/@vladfrangu/async_event_emitter/dist/index.js:282:31)
Dec 06 03:33:01 hepatitis splashtail[609387]:     at WebSocketShard.<anonymous> (/home/antiraid/splashtail/staging/bot/node_modules/@discordjs/ws/dist/index.js:1173:51)
Dec 06 03:33:01 hepatitis splashtail[609387]:     at WebSocketShard.emit (/home/antiraid/splashtail/staging/bot/node_modules/@vladfrangu/async_event_emitter/dist/index.js:282:31)
Dec 06 03:33:01 hepatitis splashtail[609387]:     at WebSocketShard.onMessage (/home/antiraid/splashtail/staging/bot/node_modules/@discordjs/ws/dist/index.js:988:14)
Dec 06 03:33:01 hepatitis splashtail[609387]: Flare (0) [ERROR] [Discord] => Uncaught Exception TypeError: Cannot read properties of undefined (reading 'length')
Dec 06 03:33:01 hepatitis splashtail[609387]:     at GuildEmoji.equals (/home/antiraid/splashtail/staging/bot/node_modules/discord.js/src/structures/GuildEmoji.js:141:21)

**Comment by Gelbpunkt** [comment]
Seems like an issue with your discord.js and less of an issue in the proxy. Unless you can provide the specific payload I can't tell you more than this.
