### ISSUE TITLE
discord.py: Can't keep up, websocket is 41.3s behind.

### ISSUE THREAD

**Issue by JohannesIBK** [Gelbpunkt/gateway-proxy#23]
Hey, when using the proxy, I get this error every few minutes after some time. It seems like it can be safely ignored or is there a real issue?

**Comment by Gelbpunkt** [comment]
discord.py can't cope with the speed that the proxy responds to heartbeats. The ping is 0ms, but discord.py doesn't immediately read the ack. In my discord.py forks I patched out headtbeating to work around this issue.

**Comment by JohannesIBK** [comment]
thank you very much
