### ISSUE TITLE
GUILD_CREATE missing `guild_scheduled_events` field

### ISSUE THREAD

**Issue by Xirado** [Gelbpunkt/gateway-proxy#26]
This does not happen on every launch for some reason but JDA doesn't like that field being missing.
Very odd that it's not reproducable consistently...

> bot-1  | 11:07:11.204 JDA [0 / 1] MainWS-ReadThr WebSocketClient      WARN   Got an unexpected Json-parse error. Please redirect the following message to the devs:
bot-1  | 	JDA 5.0.0-beta.24_d78a5e5
bot-1  | 	Unable to resolve value with key guild_scheduled_events to type DataArray: null
bot-1  | 	GUILD_CREATE -> ....

**Comment by Gelbpunkt** [comment]
That should be fixed with the latest commits.
