### ISSUE TITLE
Add self cache

### ISSUE THREAD

**Issue by Fabricio20** [Gelbpunkt/gateway-proxy#8]
Hello, it would be nice to be able to have the proxy cache self members (the member instance for the bot itself) without having to cache all members. This member has useful data such as permissions and role hierarchy.

**Comment by Gelbpunkt** [comment]
This has been added in https://github.com/Gelbpunkt/gateway-proxy/commit/1144a1d81a526344555d9964f4b1ffe0931a6c52
