### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by part1cleth1ef** [Gelbpunkt/gateway-proxy#9]
Are there any plans for k8s support (with multiple of these proxies loadbalanced or something along those lines)?

**Comment by Gelbpunkt** [comment]
Hi there, what do you have in mind exactly?

Running multiple proxies for loading balancing is already possible, though the gateway IDENTIFYs would not be ratelimit-synced. Syncing them would require adding a new single point of failure that manages the ratelimit instead, which is probably not desired.

What I can imagine being useful is not caring about failover and instead running e.g. half the shards on one proxy and half the shards on a different one, but then you'd have to hardcode the URLs for each shard, which is tedious but might work. For this to be possible I'd have to add the ability to specify a shard range to launch. Is this what you want?

**Comment by part1cleth1ef** [comment]
well, ideally workers would be able to handle the entire thing for the client end with a worker being assigned a few shards and each worker contacting the gateway proxy being able to handle it all including ratelimits and such.

**Comment by Gelbpunkt** [comment]
> well, ideally workers would be able to handle the entire thing for the client end with a worker being assigned a few shards and each worker contacting the gateway proxy being able to handle it all including ratelimits and such.

yes that's the entire idea of the proxy, but you're not really responding to my previous comment

**Comment by part1cleth1ef** [comment]
the shard range to launch could be useful.
